# 2.8.1. Ejemplo 2.4.

|Quién | Correo | Fecha | Qué hizo |
| ---  | ---   | --- | ---      |
|Michael Heredia Pérez | <mherediap@unal.edu.co> | Julio 14, 2022 | Conversión de código de MAXIMA a Python|
|Juan Nicolás Ramírez | <mherediap@unal.edu.co> | Septiembre 15, 2022 | Adecuando código|
|Michael Heredia Pérez | <mherediap@unal.edu.co> | Septiembre 19, 2022 | Cambiando comando ```.eig``` por ```.eigh``` |
|Diego Andrés Alvarez | <daalvarez@unal.edu.co>  | Febrero 19, 2024 | Mejorando los comentarios |


$$
\newcommand{\ve}[1]{{\vec{\boldsymbol{#1}}}}
\newcommand{\ma}[1]{{\boldsymbol{#1}}}
\newcommand{\hve}[1]{{\,\hat{\!\boldsymbol{#1}}}}
$$

In [1]:
import numpy as np
from sympy import init_printing, latex, symbols, Matrix

# Para imprimir bonito
init_printing()
from IPython.display import Math                 
def imprimir (texto1, variable, texto2=""):
    return Math(texto1 +  rf'{latex(variable)}' + texto2)

Considere un punto de un sólido bidimensional en el cual los esfuerzos son $\sigma_x=$ 3 Pa, $\sigma_y=$ 2 Pa y $\tau_{xy}=$ -4 Pa:

In [2]:
# Se definen los componentes de la matriz sigma
sx  =  3  # Pa
sy  =  2  # Pa
txy = -4  # Pa  

Se pide:
1. Plantear la matriz de tensiones  $\ma{\sigma}$ correspondiente.
2. Calcular el polinomio característico asociado a  $\ma{\sigma}$.
3. Calcular la dirección y magnitud de los esfuerzos principales.

## 1. Matriz de esfuerzos $\ma{\sigma}$

In [3]:
# Se define la matriz sigma
sigma = np.array([[ sx, txy], 
                  [txy, sy ]])

# Visualizamos la matriz de esfuerzos
imprimir(r"\ma{\sigma} =", Matrix(sigma))

<IPython.core.display.Math object>

## 2. Polinomio característico

Para obtener los coeficientes del polinomio característico empleamos el comando ```numpy.poly()```:

In [4]:
np.poly(sigma)

array([  1.,  -5., -10.])

Lo interpretamos como: 

$$\sigma_n^2 - 5\sigma_n -10=0$$

Y mediante la función ```numpy.roots()``` calculamos la raíces del polinomio característico, es decir, los esfuerzos principales:

In [5]:
np.roots(np.poly(sigma))

array([ 6.53112887, -1.53112887])

No olvidar que debemos garantizar por definición en el <font color='blue'>main.pdf</font> que:
$$(\sigma_1)_{xy} \geq (\sigma_2)_{xy}$$

## 3. Dirección y magnitud de los esfuerzos principales

Para calcular los valores y vectores propios de la matriz de esfuerzos $\ma{\sigma}$ con ```numpy```, empleamos el comando ```np.linalg.eigh()``` el cual retorna una lista de dos entradas, la primera contiene los valores propios y la segunda contiene los vectores propios. 

*Nota*: según la documentación de ```numpy``` existen dos comandos para obtener los valores propios de una matriz [np.linalg.eigh()](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigh.html) y [np.linalg.eig()](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html). La función ```eigh()``` se usa en vez de ```eig()``` debido a que ```eigh()``` está especialmente diseñada para el cálculo de los valores propios de matrices hermíticas; se dice que una matriz es *hermítica* cuando esta es igual a su transpuesta conjugada; en el caso de que la matriz sea real, el concepto de matriz hermítica es equivalente al concepto de matriz simétrica; en consecuencia ```eigh()``` es mucho más eficiente numéricamente hablando que ```eig()```, además en comparación a esta última, ```eigh()``` retorna los valores propios ordenados de menor a mayor; esto es posible ya que los valores propios de una matriz hermítica, y por lo tanto simétrica, son siempre números reales.

In [6]:
valp, vecp = np.linalg.eigh(sigma)

Los valores propios representan la magnitud de los esfuerzos principales, estos se almacenaron en el vector `valp`, y gracias al comando `np.linalg.eigh()` estos quedan ordenados de menor a mayor.

Los valores propios representan la magnitud de los esfuerzos principales $(\sigma_1)_{xy}$ y $(\sigma_2)_{xy}$:

In [7]:
valp  # tenga en cuenta que eigh siempre retorna los valores propios ordenados de menor a mayor

array([-1.53112887,  6.53112887])

Almacenamos en memoria como ```s1``` y ```s2```, respectivamente, para $(\sigma_1)_{xy}$ y $(\sigma_2)_{xy}$, garantizando que $(\sigma_1)_{xy} \geq (\sigma_2)_{xy}$. En particular, ```eigh()``` genera los valores propios ordenados de menor a mayor:

In [8]:
s2_xy, s1_xy = valp 

In [9]:
print(f"σ1_xy = {s1_xy:.3f} Pa")

σ1_xy = 6.531 Pa


In [10]:
print(f"σ2_xy = {s2_xy:.3f} Pa")

σ2_xy = -1.531 Pa


Los vectores propios representan las direcciones principales $\hve{n}_1$ y $\hve{n}_2$.

Los vectores propios representan las direcciones principales, estos se almacenan en el arreglo `vecp`, y corresponden a sus columnas:

In [11]:
valp

array([-1.53112887,  6.53112887])

In [12]:
vecp

array([[-0.66180256, -0.74967818],
       [-0.74967818,  0.66180256]])

Al valor propio ```s1 = 6.53112887``` le asociamos la _columna_ ```[-0.74967818, 0.66180256]``` como vector propio ```n1g``` (dirección principal 1).

Al valor propio ```s2 = -1.53112887``` le asociamos la _columna_ ```[-0.66180256, -0.74967818]]``` como vector propio ```n2g``` (dirección principal 2).

In [13]:
# Extraigo los resultados (cuidado con el orden)
n2g, n1g = vecp[:,0], vecp[:,1]

In [14]:
imprimir(r"\hve{n}^T_1 =", n1g)

<IPython.core.display.Math object>

In [15]:
imprimir(r"\hve{n}^T_2 =", n2g)

<IPython.core.display.Math object>

Verificamos que ```n1g``` sea unitario, calculando su norma con ```np.linalg.norm()```:

In [16]:
np.linalg.norm(n1g)

Verificamos que ```n2g``` sea unitario, calculando su norma con ```np.linalg.norm()```:

In [17]:
np.linalg.norm(n2g)

Por lo tanto, ```n1g``` y ```n2g``` son los vectores unitarios buscados que representan a  $\hve{n}_1$ y $\hve{n}_2$.

Así mismo, se puede calcular el ángulo de inclinación de los planos principales sobre los cuales actúan los esfuerzos principales:

In [18]:
# Calculamos el ángulo de inclinación del plano principal donde actúa s1 y s2 y 
# se convierte de radianes a grados:
t1 = np.rad2deg(np.arctan2(-n1g[1],-n1g[0]))
t2 = np.rad2deg(np.arctan2(-n2g[1],-n2g[0]))

print(f"θ1 = {t1: .4f}°")
print(f"θ2 = {t2: .4f}°")

θ1 = -41.4375°
θ2 =  48.5625°


En resumen:

* al esfuerzo principal $(\sigma_1)_{xy}$ = 6.53 Pa le asociamos la dirección principal $\hve{n}_1 = [0.75, -0.66]^T$ descrita por el ángulo $\theta_1 = -41.44^\circ$,

* al esfuerzo principal $(\sigma_2)_{xy}$ = -1.53 Pa le asociamos la dirección principal $\hve{n}_2 = [0.66, 0.75]^T$ descrita por el ángulo $\theta_2=48.56^\circ$.

Y gráficamente, nuestro sólido queda de la siguiente forma:

<img src="fig_ejem_2.8.1.png" width="600">

**Nota:** Es importante revisar el sentido de los vectores directores para así calcular correctamente el ángulo de inclinación de los planos.